---
- name: install general tools
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - screen
    - tar
    - rsync
    - wget
    - mc
    - git
    - ipvsadm
    - vim
    - libselinux-python
    - nfs-utils
    - ntp
    - ntpdate

- name: disable firewalld
  service: name=firewalld state=stopped enabled=no

- name: permit selinux
  selinux:
    policy: targeted
    state: permissive

- name: disable selinux
  selinux: state=disabled

- name: enable nfs
  service: name=nfs state=started enabled=yes

- name: enable ntpdate
  service: name=ntpdate state=started enabled=yes

- name: set timezone to Europe/Moscow
  timezone:
    name: Europe/Moscow

- name: check if go need to be installed
  command: go version
  register: go_version_result
  ignore_errors: True
  changed_when: false

- name: import go setup recipe
  include_tasks: go.yaml
  when: go_version_result|failed

- name: Build hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: '{{ hostvars[item].ansible_default_ipv4.address }} {{item}}'
    state: present
  with_items: '{{ groups["all"] }}'
