---
- name: prepare secrets directory
  file:
    path: "{{ secrets_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: fill master secrets
  template:
    src: "templates/{{ item }}"
    dest: "{{ secrets_dir }}/{{ item }}"
    owner: root
    group: root
    mode: '0600'
  with_items: "{{ secrets_master_map }}"
  when: ansible_nodename == groups['master'][0]

- name: fill mware secrets
  template:
    src: "templates/{{ item }}"
    dest: "{{ secrets_dir }}/{{ item }}"
    owner: root
    group: root
    mode: '0600'
  with_items: "{{ secrets_mware_map }}"
  when: ansible_nodename == groups['mware'][0]

- name: fill s3 secrets
  template:
    src: "templates/{{ item }}"
    dest: "{{ secrets_dir }}/{{ item }}"
    owner: root
    group: root
    mode: '0600'
  with_items: "{{ secrets_s3_map }}"
  when: ansible_nodename == groups['s3'][0]
