---
- name: prepare secrets directory
  file:
    path: "{{ secrets_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0700

- name: fill secrets
  file:
    path: "{{ secrets_dir }}/{{ item }}"
    state: touch
    owner: root
    group: root
    mode: 0600
  with_items: "{{secrets_gate_map }}"
