---
- name: install common ceph components
  dnf:
    name: '{{ item }}'
    state: present
  with_items:
    - ceph-deploy
    - ceph

- name: create cehp users
  user:
    name: ceph
    home: /home/ceph
    password: '{{ ceph_user_hashed_passwd }}'
    state: present
  register: cehp_user

- name: prepare ceph admin directory
  file:
    path: /home/ceph/ceph-admin
    state: directory
    owner: ceph
    group: users
    mode: 0755
  when: cehp_user.changed == True

- name: configure ceph users
  shell: |
    echo "ceph ALL = (root) NOPASSWD:ALL" > /etc/sudoers.d/ceph
    chmod 0440 /etc/sudoers.d/ceph
    chown -R ceph:users /home/ceph/
  when: cehp_user.changed == True

- name: copy autorized keys
  authorized_key:
    user: ceph
    state: present
    key: '{{ item }}'
  with_file:
    - templates/id_rsa.pub
  when: cehp_user.changed == True

- name: find out authorized keys
  shell: ssh-keyscan -T 10 -t ecdsa {{ item }}
  register: ssh_known_hosts
  ignore_errors: yes
  with_items:
    - "{{ groups['s3admin'] }}"
    - "{{ groups['s3nodes'] }}"
  when: cehp_user.changed == True

- name: prepare known_hosts
  file:
    path: /home/ceph/.ssh/known_hosts
    owner: ceph
    group: users
    state: touch
  when: cehp_user.changed == True

- name: update known_hosts
  known_hosts:
    name: "{{ item.item }}"
    key: "{{ item.stdout }}"
    path: /home/ceph/.ssh/known_hosts
    state: present
  with_items: "{{ ssh_known_hosts.results }}"
  when: cehp_user.changed == True

- name: import master tasks
  include_tasks: ceph.yaml
  when: cehp_user.changed == True
