---
- name: install kuebrnetes
  dnf:
    name: '{{ item }}'
    state: present
  with_items:
    - kubernetes

- name: configure kubernetes master
  lineinfile:
    path: /etc/kubernetes/config
    regexp: '^{{ item.name }}'
    line: '{{ item.name }} = {{ item.value }}'
    backup: yes
  register: kuebrnetes_changed
  with_items: '{{ kube_master_conf_t }}'

- name: configure kubelet
  lineinfile:
    path: /etc/kubernetes/kubelet
    regexp: '^{{ item.name }}'
    line: '{{ item.name }} = {{ item.value }}'
    backup: yes
  register: kubelet_changed
  with_items: '{{ kubelet_conf_t }}'

- name: restart kubernetes services
  service:
    name: '{{ item }}'
    state: restarted
    enabled: yes
  with_items:
    - kube-proxy
    - kubelet
  when: kuebrnetes_changed.changed or kubelet_changed.changed
