---
- name: install docker
  dnf:
    name: docker
    state: present
  register: docker_installed

- name: prepare docker drive
  shell: |
    rm -rf /var/lib/docker
    pvcreate {{ docker_drive }}
    vgcreate docker {{ docker_drive }}
    lvcreate --wipesignatures y -n thinpool docker -l 95%VG
    lvcreate --wipesignatures y -n thinpoolmeta docker -l 1%VG
    lvconvert -y --zero n -c 512K --thinpool docker/thinpool --poolmetadata docker/thinpoolmeta
  when: docker_installed.changed

- name: copy templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    backup: yes
  with_items:
    - { src: "templates/docker-thinpool.profile", dest: "/etc/lvm/profile/docker-thinpool.profile" }
    - { src: "templates/daemon.json", dest: "/etc/docker/daemon.json" }
  when: docker_installed.changed

- name: change /etc/sysconfig/docker-storage-setup
  lineinfile:
    path: /etc/sysconfig/docker-storage-setup
    regexp: '^STORAGE_DRIVER.*'
    line: 'STORAGE_DRIVER=""'
    backup: yes
  when: docker_installed.changed

- name: activate the pool and start docker
  shell: |
    lvchange --metadataprofile docker-thinpool docker/thinpool
    systemctl start docker
  when: docker_installed.changed

- name: enable docker
  service: name=docker state=started enabled=yes
  when: docker_installed.changed
