---
- name: install mariadb for keystone sake
  dnf:
    name: '{{ item }}'
    state: present
  with_items:
    - mariadb
    - mariadb-server-utils
  register: mariadb_installed

- name: enable mariadb
  service: name=mariadb state=started enabled=yes
  when: mariadb_installed.changed

- name: set mariadb root password
  shell: |
    mysqladmin -u root password "{{ ks_db_root_pass }}"
    mysql -u root --password={{ ks_db_root_pass }} -c mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY '{{ ks_db_root_pass }}' WITH GRANT OPTION;"
  when: mariadb_installed.changed

- name: configure mariadb keystone database
  shell: |
    mysql -u root --password={{ ks_db_root_pass }} -c mysql -e "CREATE DATABASE {{ ks_db_name }};"
    mysql -u root --password={{ ks_db_root_pass }} -c mysql -e "GRANT ALL PRIVILEGES ON {{ ks_db_name }}.* TO {{ ks_db_user}}@localhost IDENTIFIED BY '{{ ks_db_pass }}';"
    mysql -u root --password={{ ks_db_root_pass }} -c mysql -e "GRANT ALL PRIVILEGES ON {{ ks_db_name }}.* TO {{ ks_db_user}}@'%' IDENTIFIED BY '{{ ks_db_pass }}';"
  when: mariadb_installed.changed

- name: import keystone tasks
  include_tasks: keystone.yaml
