---
- name: install docker
  dnf:
    name: docker
    state: present
- name: enable docker
  service: name=docker state=started enabled=yes

- name: prepare docker drive
  shell: |
    systemctl stop docker
    rm -rf /var/lib/docker
    pvcreate {{ docker_drive }}
    vgcreate docker {{ docker_drive }}
    lvcreate --wipesignatures y -n thinpool docker -l 95%VG
    lvcreate --wipesignatures y -n thinpoolmeta docker -l 1%VG
    lvconvert -y --zero n -c 512K --thinpool docker/thinpool --poolmetadata docker/thinpoolmeta

- name: copy templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    backup: yes
  with_items:
    - { src: "templates/docker-thinpool.profile", dest: "/etc/lvm/profile/docker-thinpool.profile" }
    - { src: "templates/daemon.json", dest: "/etc/docker/daemon.json" }

- name: activate the pool and start docker with kubelet
  shell: |
    lvchange --metadataprofile docker-thinpool docker/thinpool
    systemctl start docker
