---
listen: "{{ groups['master'][0] }}:8687"
gate: "{{ groups['master'][0] }}:8686"
keystone:
        address: "{{ groups['master'][0] }}:5000"
        domain: "swifty"
        admin: "admin"
        pass: "KSPASS"
db:
        address: "127.0.0.1:27017"
        user: "swyadmd"
        password: "DBAPASS"
