---
daemon:
        address: "{{ groups['master'][0] }}:8687"
        https:
                cert: "/etc/swifty/ca/server.crt"
                key: "/etc/swifty/ca/server.key"
gate: "{{ groups['master'][0] }}:8686"
keystone:
        address: "{{ groups['master'][0] }}:5000"
        domain: "swifty"
        admin: "admin"
        pass: "KSPASS"
db: "swyadm:DBAPASS@127.0.0.1:27017"
