---
db: "swifty-s3:MGOS3PASS@{{ groups['master'][0] }}:27017"
daemon:
        address: "{{ groups['s3'][0] }}:8787"
        admport: "8789"
        token: "S3TOKEN"
        loglevel: "debug"
notify:
        rabbitmq:
                target: "{{ groups['master'][0] }}:5672/s3"
                user: "s3"
                password: "RMQS3PASS"
secretskey: "S3SECRETSKEY"
ceph:
        config-path: /etc/swifty/conf/ceph.conf
